version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cupboardy
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: python_app_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: cupboardy
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "sleep 5 && flask --app app.py run --host=0.0.0.0 --port=4000"]

volumes:
  db_data:
